### ISSUE TITLE
Not able to quit chromium from rPi2

### ISSUE THREAD

**Issue by indefinit** [OpenframeProject/Openframe#11]
I'm looking to quit a website run in chromium and I press CTRL+C or ESC but neither quits Chromium.  Images/shaders quit on CTRL+C fine.

**Comment by jmwohl** [comment]
Ah, right — try CTRL+W (maybe twice?). Since chromium is running in X, it doesn't respond to the usual terminal-y commands until you close out of the X session.

The website extension is the least-well tested at present. We'd like to figure out an easy way to get WebGL running correctly...

**Comment by jmwohl** [comment]
Added a note about this in the docs — closing this issue.
