### ISSUE TITLE
login-popup login failure: ofsdk.js 404

### ISSUE THREAD

**Issue by meetar** [OpenframeProject/Openframe#19]
When exporting a shader from editor.thebookofshaders.com, when I click the "LOG IN" button, nothing occurs, and the console reads:

    http://openframe.io/js/ofsdk.js Failed to load resource: the server responded with a status of 404 (Not Found) 
    login-popup:67 clicked
    login-popup:69 Uncaught ReferenceError: OF is not defined

<img width="634" alt="screen shot 2016-07-07 at 4 54 54 pm" src="https://cloud.githubusercontent.com/assets/459970/16669451/955d89c6-4463-11e6-9f85-659443121a34.png">

Seen on Mac OS X, Chrome 51. (The popup doesn't appear at all in FF and Safari)

**Comment by jmwohl** [comment]
Thanks for reporting this — the JS sdk was moved, so likely this hasn't been working for quite a while! Should be an easy fix, will try to get to it soon.

**Comment by jmwohl** [comment]
This was a problem in the [Openframe-APIServer](https://github.com/OpenframeProject/Openframe-APIServer) repo. I just pushed a patch release that fixes it — closing this issue.

Also submitted a PR that should get the popup working in Firefox. Safari requires disabling of the popup blocker.

https://github.com/OpenframeProject/Openframe-APIServer/releases/tag/v0.3.1
