### ISSUE TITLE
javascript and canvas?

### ISSUE THREAD

**Issue by nosarious** [OpenframeProject/Openframe#25]
I had hoped to explore some webGL stuff, but it appears that may not be working for some of the different websites I tried. 
   https://threejs.org/examples/webgl_shader.html
I then tried some websites with canvas driven artwork.
   http://www.kevs3d.co.uk/dev/plasma/
   http://glimr.rubyforge.org/cake/demos/fireworks2.6rt.html
(this should be a chromium-specific site)
   http://www.sketchpatch.net/livecodelab/index.html#bookmark=springysquaresDemo
Those don't work either.

is there anyway to tell what 'will' work with a website? I know you use Chromium  (I'm assuming the Chromium which is included on the raspberry pi) 

There are various error codes having to do with images or simple messages like "terminated" when I try some of these things.

Is there a list I am missing on what 'will' work and what will not when one uses a website? I would like to consider a simple slideshow of images and perhaps text, but I am limited in terms of how much time I can spend experimenting.

**Comment by jmwohl** [comment]
Yeah, unfortunately webGL does not yet work on Openframe — although it's possible to get webGL working in chromium by enabling the experimental GL feature on the Pi, it breaks other things. It's high on our wish list though, so hopefully future versions will support webGL by default.

Websites that use canvas *should* work, but the the Pi is not a fast machine, so they might run SUPER slow if they are performing a ton of calculations on the CPU. The examples you tried all seem pretty heavy, and I'm not surprised that they don't seem to work at all.

In answer to your question, we don't have a list anywhere of what will and won't work for websites — but that is a great idea, and we should. I'll add an issue about that on the [Openframe-Website](https://github.com/OpenframeProject/Openframe-Website) extension repo. We're slowly but surely updating docs, and this type of info should go in there.

FWIW, a simple slideshow of images and text should not be a problem at all.

**Comment by nosarious** [comment]
Thank you very much for the response. I  suspected that was the reason, and I will try to experiment with the various formats I would like to explore.

**Comment by jmwohl** [comment]
Closing — I've added a [related issue](https://github.com/OpenframeProject/Openframe-Website/issues/9) on the Openframe-Website repo.

**Comment by jeremydouglass** [comment]
WEBGL now works fine in a new install of Openframe with Openframe-Website. Tested with a shader link above (https://threejs.org/examples/webgl_shader.html) and with a p5.js web editor sketch in WEBGL mode.

**Comment by jvolker** [comment]
I recognised that too but think it works on a Pi4 only.

**Comment by jeremydouglass** [comment]
WEBGL is running here on a Pi 3b+

**Comment by jvolker** [comment]
Let's continue this conversation here: https://github.com/OpenframeProject/Openframe-Website/issues/9
