### ISSUE TITLE
TypeError: pm.init is not a function

### ISSUE THREAD

**Issue by mattun** [OpenframeProject/Openframe#35]
now i tried DEBUG=* npm test .

TypeError: pm.init is not a function
at Context.<anonymous> (test/plugin-manager.spec.js:18:8)

I think plugin-manager version is not correct?
(before one problem, apeared message can not find plugin-manager, so I changed plugin-manager.spec.js header  pm = require('../plugin-manager'); to pm = require('plugin-manager');
and npm install plugin-manager --save)

**Comment by jmwohl** [comment]
Yeah sorry — the tests are neither complete nor up to date. Would be great to see someone contribute to the test suite :D...

To clarify one thing, the 'plugin-manager' module is an internal module, and was renamed [extension-manager](https://github.com/OpenframeProject/Openframe/blob/master/src/extension-manager.js). It has no relation to [this plugin-manager module in npm](https://www.npmjs.com/package/plugin-manager).

**Comment by mattun** [comment]
Thanks for reply , I try install again
