### ISSUE TITLE
Allow to pass functions to the `end_command` in extensions

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe#43]
Sometimes it's necessary to do some cleanup tasks after finishing to show some artwork. 

While it's currently possible to run a shell script by passing a string via the `end_command` property, it would be nice to do this directly in Node.Js by passing a function instead. Just like it's possible for`start_command`.

I had a quick look into the code, and it seems it's only necessary to copy a few lines of code to allow this.

Thanks.

**Comment by jmwohl** [comment]
Yeah, I don't see a reason not to support this... feel free to submit a PR!
